[package]
name = "omdb"
version = "0.1.0"
authors = ["Brandon Aldrich <brandon@aldr.io>"]
description = "OMDb API for Rust"
documentation = "https://aldrio.github.io/omdb-rs/omdb/"
homepage = "https://github.com/aldrio/omdb-rs"
repository = "https://github.com/aldrio/omdb-rs"
readme = "README.md"
license = "MIT"
build = "build.rs"

[build-dependencies]
serde_codegen = "0.7.10"

[dependencies]
hyper = "0.9.8"
serde = "0.7.10"
serde_json = "0.7.1"